<h2 style="color:red;"><?php echo $this->__('Table Group') ?></h2>
<?php $models = Mage::getModel('membership/group')->getCollection()
						->setOrder('group_id','ASC');?>
<?php if(count($models) == null){?>
	<h4><?php echo $this->__('Table group is empty');?></h4>
<?php return;}?>	
<div style="overflow-x:auto;">
	<table class="table">	 
		<thead>
			<tr class="row">
				<th style="text-align:center;"><?php echo $this->__('Group') ?></th>
				<?php foreach($models as $model){ ?>
				<th style="width:300px;"><?php echo $model->getGroupName() ?></th>
				<?php }?>
			</tr>
		</thead>
		<tbody>
		<?php foreach($models as $model){ ?>
			<tr class="col">		
				<th class="name"  width= "10%"><?php echo $model->getGroupName()?></th>
			  
			<?php $collections = Mage::getModel('membership/groupprice')->getCollection()
								->addFieldToFilter('group_from', $model->getGroupId())
								->setOrder('group_from','ASC')
								->setOrder('group_to','ASC');?>
			<?php foreach($collections as $collection){?>           
				<td><input style="width:300px;" name="groupprice[]" value="<?php echo $collection->getPrice();?>"></input></td> 
					
		   <?php }?>
		   </tr>
		<?php }?>
		</tbody>		 
	</table>
</div>
<style>
.table {
    border: 1px solid black;
}
.row {
    background-color: #4CAF50;
    color: white;
	text-align: center;
}
.name {
    background-color: #4CAF50;
    color: white;
	text-align:center;
}
</style>
