<h2 style="color:red;"><?php echo $this->__('Config fee exchange group product') ?></h2>
<?php $models = Mage::getModel('membership/group')->getCollection();?>
<?php if(count($models) == null){?>
	<h4><?php echo $this->__('Table group is empty');?></h4>
<?php return;}?>	
<div style="overflow-x:auto;">
	<table class="table" id="config-fee-table">
		<thead>
			<tr class="row">
				<th style="text-align:center;"><?php echo $this->__('Group') ?></th>
				<?php foreach($models as $model){ ?>
				<th style="text-align: center"><?php echo $model->getGroupName() ?></th>
				<?php }?>
			</tr>
		</thead>
		<tbody>
		<?php foreach($models as $model){ ?>
			<tr class="col">		
				<td class="name"><?php echo $model->getGroupName()?></td>
			  
			<?php $collections = Mage::getModel('membership/groupprice')->getCollection()
								->addFieldToFilter('group_from', $model->getGroupId());?>
			<?php foreach($collections as $collection){?>           
				<td><input type="text" name="groupprice[]" value="<?php echo $collection->getPrice();?>"></input></td> 
					
		   <?php }?>
		   </tr>
		<?php }?>
		</tbody>		 
	</table>
</div>
<style>
#config-fee-table {
    border: 1px solid black;
}
#config-fee-table .row {
    background-color: #4CAF50;
    color: white;
	text-align: center;
}
#config-fee-table .name {
    background-color: #4CAF50;
    color: white;
	text-align:center;
}
#config-fee-table tbody tr td{
	padding: 10px;

#config-fee-table th{
	padding: 5px !important;
}
</style>
