<div class="ms-membership">
    <div class="page-title form-group">
        <h1><?php echo $this->__('My exchange product') ?></h1>
    </div>
    <?php
    $listProductBoughts = $this->getListProductBoughtsCanExchange();
    $listGroupProductExchanges = $this->getGroupProductExchange();
    $transactions = $this->getTransaction();
    ?>
    <h2><?php echo $this->__('My exchange') ?></h2>
    <?php if (!count($listProductBoughts)) { ?>
        <p class="note-msg"><?php echo $this->__('You dont not product to exchange.') ?></p>
    <?php } else {
        ?>
        <form action="<?php echo $this->getExchangeProduct() ?>" method="post">
            <button type="submit">TEST</button>
            <div class="table-responsive form-group">
                <table class="packages-table table table-bordered table-hover" id="myplan-table">
                    <thead>
                    <tr>
                        <th class="first"><?php echo $this->__('Product boughts') ?></th>
                        <th><?php echo $this->__('Product exchange') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="first col-sm-5 col-xs-5 col-tn-5">
                            <?php foreach (array_keys($listProductBoughts) as $productId): ?>
                                <?php $listProductBought = $this->getProduct($productId);
                                if (!$this->isGroupProduct($listProductBought->getId()))
                                    continue;
                                ?>
                                <div class="row">
                                    <div class="f-product col-sm-12 col-xs-12 col-tn-12">
                                        <input type="radio" name="group-radio-product-boughts"
                                               value="<?php echo $listProductBought->getId() ?>">
                                        <input type="text" style="display: none"
                                               name="number-product-bought-<?php echo $listProductBought->getId() ?>"
                                               value="<?php echo $listProductBoughts[$listProductBought->getId()] ?>">

                                        <a class="product-image text-center"
                                           href="javascript:checkradiobox(<?php echo $listProductBought->getId() ?>);">
                                            <?php $_imgHtml = '';
                                            if ($listProductBought->getSmallImage()) {
                                                $_imgHtml = '<img src="' . $this->helper("catalog/image")->init($listProductBought, "small_image")->resize(100) . '" width="100" height="100" alt="' . $this->stripTags($this->getImageLabel($listProductBought, "small_image"), null, true) . '" />';
                                            } else {
                                                $_imgHtml = '<img src="' . Mage::getBaseUrl("media") . 'megamenu/sample_data/small_image.jpg" alt="' . $this->stripTags($listProductBought->getName(), null, true) . '" title="' . $this->stripTags($listProductBought->getName(), null, true) . '"/>';
                                            }
                                            echo $_imgHtml;
                                            ?>
                                        </a>
                                        <table class="product-info-exchange">
                                            <tbody>
                                            <tr>
                                                <td><a class="product-name" style="text-align: center"
                                                       href="<?php echo $listProductBought->getProductUrl(); ?>"><strong><?php echo $listProductBought->getName(); ?></strong>
                                                    </a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <?php echo $this->__('Group product: ') . $this->isGroupProduct($listProductBought->getId()); ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <?php echo $this->__('Price: ') . Mage::helper('membership')->getDiscountPrice(null, $listProductBought->getId()); ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <?php echo $this->__('Qty can exchange: ') . $listProductBoughts[$listProductBought->getId()]; ?>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </td>
                        <td class="col-sm-7 col-xs-7 col-tn-7">
                            <?php $listGroup = array_keys($listGroupProductExchanges);
                            foreach ($listGroup as $groupId) { ?>

                                <?php $listproduct = $listGroupProductExchanges[$groupId];
                                ?>
                                <div class="col-sm-12 col-xs-12 col-tn-12">
                                    <h2>
                                        <?php echo $groupId; ?>
                                    </h2>
                                    <?php $i = 1;
                                    foreach ($listproduct as $productExchange):
                                        $productExchange = $this->getProduct($productExchange); ?>

                                        <div class="row">
                                            <div class="f-product col-sm-12 col-xs-12 col-tn-12">
                                                <input type="radio" name="group-radio-product-exchange"
                                                       value="<?php echo $productExchange->getId() ?>">
                                                <a class="product-image text-center"
                                                   href="javascript:checkradioboxexchange(<?php echo $productExchange->getId() ?>);">
                                                    <?php $_imgHtml = '';
                                                    if ($productExchange->getSmallImage()) {
                                                        $_imgHtml = '<img src="' . $this->helper("catalog/image")->init($productExchange, "small_image")->resize(100) . '" width="100" height="100" alt="' . $this->stripTags($this->getImageLabel($productExchange, "small_image"), null, true) . '" />';
                                                    } else {
                                                        $_imgHtml = '<img src="' . Mage::getBaseUrl("media") . 'megamenu/sample_data/small_image.jpg" alt="' . $this->stripTags($productExchange->getName(), null, true) . '" title="' . $this->stripTags($productExchange->getName(), null, true) . '"/>';
                                                    }
                                                    echo $_imgHtml;
                                                    ?>
                                                </a>

                                                <table class="product-info-exchange">
                                                    <tbody>
                                                    <tr>
                                                        <td><a class="product-name" style="text-align: center"
                                                               href="<?php echo $productExchange->getProductUrl(); ?>"><strong><?php echo $productExchange->getName(); ?></strong>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <?php echo $this->__('Group product: ') . $this->isGroupProduct($productExchange->getId()); ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <?php echo $this->__('Price: ') . Mage::helper('membership')->getDiscountPrice(null, $productExchange->getId()); ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <input type="text"
                                                                   name="number-exchange-<?php echo $productExchange->getId() ?>">
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <?php $i++; endforeach; ?>
                                </div>


                            <?php } ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </form>
    <?php } ?>

    <h2><?php echo $this->__('My Transaction') ?></h2>
    <?php if (!count($transactions)) { ?>
        <p class="note-msg"><?php echo $this->__('You dont not transaction') ?></p>
    <?php } else {
        ?>
        <div class="table-responsive form-group">
            <table class="packages-table table table-bordered table-hover" id="packages-table">
                <thead>
                <tr>
                    <th class="first"><?php echo $this->__('Date') ?></th>
                    <th><?php echo $this->__('Product Old') ?></th>
                    <th><?php echo $this->__('Product New') ?></th>
                    <th><?php echo $this->__('Detail Transaction') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($transactions as $transaction) { ?>
                    <tr>
                        <td class="first"><?php echo $this->formatDate($transaction->getTransactionTime(), 'short', true) ?></td>
                        <td><?php echo Mage::getModel('catalog/product')->load($transaction->getProductIdOld())->getName() ?></td>
                        <td><?php echo Mage::getModel('catalog/product')->load($transaction->getProductIdNew())->getName() ?></td>
                        <td><?php echo $transaction->getDetailTransaction() ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    <?php } ?>
</div>


<script>
    function checkradiobox(productId) {

        var checked = $$('input[name="group-radio-product-boughts"][value=' + productId + ']')[0].checked;
        if (checked == false) {
            $$('input[name="group-radio-product-boughts"][value=' + productId + ']')[0].checked = true;
        } else {
            $$('input[name="group-radio-product-boughts"][value=' + productId + ']')[0].checked = false;
        }

    }
    function checkradioboxexchange(productId) {
        var checked = $$('input[name="group-radio-product-exchange"][value=' + productId + ']')[0].checked;
        if (checked == false) {
            $$('input[name="group-radio-product-exchange"][value=' + productId + ']')[0].checked = true;
        } else {
            $$('input[name="group-radio-product-exchange"][value=' + productId + ']')[0].checked = false;
        }

    }
    jQuery(document).ready(function () {
        jQuery("#owl-demo-2").owlCarousel({
            items: 2,
            navigation: true
        });
        jQuery("#owl-demo-1").owlCarousel({
            items: 2,
            navigation: true
        });

        jQuery('div.row a').css('float', 'left');
        jQuery('div.row input[type="radio"]').css('float', 'left');
    });


</script>
<style>
    .product-info-exchange {
        margin-left: 2px;
    }

    a.product-image.text-center {
        margin-right: 10px;
        margin-left: 10px;
    }

    .table-exchange-product {
        width: 100%;
    }

    table.table-exchange-product td a {
        float: none !important;
        text-align: center;
    }

    table.table-exchange-product td {
        text-align: center;
    }

    .table-exchange-product a img {
        margin-left: auto;
        margin-right: auto;
    }
</style>